export const GEOLOCATION_SUCCESS = 'GEOLOCATION_SUCCESS';
export const GEOLOCATION_FAILURE = 'GEOLOCATION_FAILURE';
export const FETCH_WEATHER_BEGIN = 'FETCH_WEATHER_BEGIN';
export const FETCH_WEATHER_SUCCESS = 'FETCH_WEATHER_SUCCESS';
export const FETCH_WEATHER_FAILURE = 'FETCH_WEATHER_FAILURE';
